export const trees = [
    {
        sk: {
            title: "Jaseň",
            location: "Garhválske Himaláje",
            protest: "Hnutie Chipko",
            dating: "od roku 1973",
            story: "Hnutie Chipko vzniklo, keď do miestneho lesa prišli drevorubači, aby vyrúbali 300 stromov na výrobu tenisových rakiet. Dedinčania, najmä ženy, sa podujali chrániť ho bubnovaním a krikom. Počas ďalšieho protestu bránili stromy vlastnými telami – objímali ich. Vytrvali aj napriek hrozbám drevorubačov, ktorí po štyroch dňoch odišli. Odvtedy sa objímanie stromov stalo stratégiou hnutia a nadobudlo takú silu, že štát rozhodol v prospech dedinčanov a lesov.",
        },
        en: {
            title: "Ash Tree",
            location: "Garhwal Himalayas",
            protest: "Chipko Movement",
            dating: "since 1973",
            story: "The Chipko Movement started when loggers came to the local forest to cut down 300 trees to make tennis rackets.The villagers, especially women, decided to protect their forest by beating drums and shouting.In another protest, they defended trees with their bodies by hugging the trees.Despite the threats of the loggers, they persevered.After four days the loggers left.Embracing the trees then became a strategy of the movement.It was so strong that the state decided in favour of the villagers and the forests.",
        },
        poem: "By the roadside, a woman waits for the bus: The forest she came to see, the stream, all gone. She tells of her sadness and pain to the vendor of tea.\n\nTo which the vendor of tea replies: There is hope now. The women in the valley ’ve started saying they\n\nwon’t let the trees be cut down.[1]\n\n\nThe women, they’ve started to march, and they embrace the trees, and they stay until the loggers leave\n\n\n—the entire night they kept guard of the trees, and the following morning\n\nmore villagers came, they take turns,\n\nthey rotate who’s by the trees and who’s by the children.\n\n\nTennis racquets? What the hell\n\nTennis racquets? What the hell\n\n\nIn its permanence, the forest is our economy,\n\nthe women said",
        references: "[1] based on a story told by Vandana Shiva in various interviews.",
        performers: "Eva Šušková, Peter Mazalán",
    },
    {
        sk: {
            title: "Dub letný „Vládca juhu“",
            location: "Bielovežský prales",
            protest: "",
            dating: "2017 – 2024",
            story: "Keď strážnici v poľskom Bielovežskom pralese násilne vykázali ochranárov, ktorí chceli zastaviť výrub stromov v jednom z posledných pralesov v Európe, Európska únia im pohrozila žalobou. Aktivisti za ochranu prírody sa pripútali reťazami k ťažobným zariadeniam v lese, ktorý je súčasťou svetového dedičstva UNESCO a rozprestiera sa pri hraniciach s Bieloruskom. Rastú v ňom staré majestátne stromy, najmä duby – niektoré z nich majú vlastné mená, napríklad jeden z najväčších sa volá „Vládca juhu“.\n\nPäť rokov od environmentálnych protestov je prales svedkom ďalšej politickej krízy – migranti a utečenci, najmä z Blízkeho východu a Afriky, sa snažia prekročiť hranice EÚ medzi Bieloruskom a Poľskom cez Bielovežský prales. Migranti ho \nnazvali „džungľou“, pretože prejsť cez túto prírodnú rezerváciu a prežiť v nej je veľmi náročné. Mnohí sa skrývajú pred pohraničnou strážou a sú zatláčaní z oboch strán hranice, zostávajú tak dlhodobo uväznení v lese, kde čelia drsnému počasiu, hladu a dokonca aj smrti.",
        },
        en: {
            title: "European Oak “Emperor of the South”",
            location: "Białowieża Forest",
            protest: "",
            dating: "2017–2024",
            story: "When security guards in Poland's Bialowieza Forest forcibly ejected protesters who sought to stop the felling of trees in one of Europe's last primeval woods, it drew the threat of a European Union lawsuit. The environmental campaigners chained themselves to logging equipment in the forest, a UNESCO World Heritage site straddling the Belarus border. It is home to large ancient trees, especially oaks – some bearing names such as “Emperor of the South”.\n\nFive years after the environmental protests, the primeval forest witnessed another political crisis – migrants and refugees, mainly from the Middle East and Africa, tried to cross the EU border between Belarus and Poland through the Bialowieza Forest. It was dubbed ‘The Jungle’ by migrants, as this nature reserve is difficult to cross and challenging to survive. Having to hide from the border guards and being pushed back from both sides of the border, many found themselves trapped in the forest for a long time, facing harsh weather, starvation, and even death.",
        },
        poem: "Does elegy have rules?\n\nDo the rules soothe the grief?\n\nThe child who froze at my roots\n\nThe people who fight at two fronts: for the child\n\n          and for me\n\n\n\nEmperor of the South: the tree shows no clear signs of dying",
        performers: "Peter Mazalán",
    },
    {
        sk: {
            title: "Borovica limbová",
            location: "Vysoké Tatry",
            protest: "protest v Tichej a Kôprovej doline",
            dating: "2007",
            story: "Po ničivej veternej smršti v slovenskom národnom parku, ktorá vyvrátila veľkú časť borovicového lesa, začal štátny podnik spracovávať drevo. Tvrdili, že odstránenie dreva zabráni šíreniu kôrovca a požiarov. Odborníci upozornili, že tým porušili zákon o ochrane prírody, keďže na zásah do biotopu európskeho významu nemali povolenie. Začali sa protesty na ochranu prírodného územia Tichej a Kôprovej doliny pred ťažbou a výrubom dreva, aby sa les mohol prirodzene obnoviť. Nasledovali policajné zatýkania a súdne konanie, ktoré napokon rozhodlo, že obnova divých lesov v Kôprovej a Tichej doline sa prenechá prírodným procesom.\n\nV tejto oblasti rastú aj najstaršie stromy na Slovensku – borovice limbové (Pinus cembra) – niektoré majú vyše 1000 rokov. Borovica limbová nie je všedný strom. V nižších polohách ju vytlačili iné druhy, ale pod vrcholmi tatranských skalnatých štítov sa darí iba jej, potrebuje málo pôdy, mach a rastie aj na skalách.",
        },
        en: {
            title: "Arolla Pine",
            location: "High Tatras",
            protest: "Tichá Valley and Kôprová Valley protest",
            dating: "2007",
            story: "After a wind calamity in which large areas of pine forest in a Slovak national park were uprooted, the state company started to process the wood. They claimed that removal of the wood would avoid the spread of bark beetles and fires. Conservationists, however, declared that it violated nature protection laws and that they do not have authorisation to intervene in a habitat of European importance. They began a protest to protect the natural area of the Tichá and Kôprová valley from logging and harvesting of wood, and to maintain natural renewal of the forest. After police detentions and a legal battle, it was eventually decided that the Kôprová and Tichá valley would be left to renew naturally as a wild forest.\n\nThis area is home to the oldest trees in Slovakia – Arolla pines (Pinus cembra), possibly more than 1,000 years old. The Arolla pine is no ordinary tree; on the lowlands, it was displaced by other species, but under the peaks of the rocky Tatra mountains it is the only one that thrives, requiring just a little soil and moss, and even growing on rock.",
        },
        poem: "The respect one feels towards trees that bear nuts\n\n\nThe respect one feels towards trees that bear nuts\n\nat the upper limit of the forest belt\n\n\nThe respect one feels towards trees that need no soil almost,\n\ngrow on rock\n\nwithstand wind\n\nThe roots of the cembra pine stabilise           stabilise soil\n\nprotect against avalanche\n\n\nThe sky darkened as the gale gathered that November night\n\nIt was three years before the loggers arrived here, and so did we, winning time.\n\n\nLoggers at the ministry\n\nPoachers at the ministry\n\nHunters at the ministry.\n\n\n\nWe stand, we sail, we do not mourn, we curse\n\nWhat will protect you?\n\nIn vessels of stone pine the milk will not sour, the water will not spoil\n\nWe stand, we sail, we do not mourn, we curse\n\nWhat will protect you?\n\n\nLoggers at the ministry\n\nPoachers at the ministry\n\nHunters at the ministry.\n\n\n\nAt night we feel as a species again,\n\ntrapped by our shared biology.",
        performers: "Anna Čonková, Peter Mazalán",
    },
    {
        sk: {
            title: "Perrierov baobab",
            location: "Severný Madagaskar",
            protest: "",
            dating: "",
            story: "Perrierov baobab (lat. Adansonia Perrieri) patrí medzi najohrozenejšie madagaskarské baobaby. Je zapísaný v Červenom zozname, ktorý nedávno označil jeho ohrozenie za kritické, keďže na severnom Madagaskare zostalo menej ako 200 týchto endemických stromov. Ohrozujú ho klimatické zmeny a úbytok biotopov v dôsledku požiarov, výrubu na ťažbu dreveného uhlia a dreva, ako aj výstavby baní. V tejto oblasti Madagaskaru sú rozšírené zafírové bane, ktoré poškodzujú životné prostredie.\n\nSmutný príbeh stromu zdôrazňuje aj jeho názov. Joseph Marie Henry Alfred Perrier de la Bâthie bol francúzsky botanik, ktorého meno nesie tento „objavený“ druh. Avšak práve Perrier v roku 1924 priniesol na madagaskarský ostrov červca nopálového, aby zabránil strategickému vysádzaniu kaktusov opuncia miestnymi obyvateľmi. Červec sa ako škodca rýchlo rozšíril po celom ostrove, spôsobil hladomor a rozsiahle spoločenské zmeny.",
        },
        en: {
            title: "Perrier's Baobab",
            location: "Northern Madagascar",
            protest: "",
            dating: "",
            story: "Perrier's baobab, in Latin Adansonia Perrieri, is one of Madagascar's most endangered baobabs. Endemic to northern Madagascar, fewer than 200 of these trees remain, placing it at high risk of extinction – its inclusion on the Red List recently suggested critical endangerment. The tree faces threats from climate change and from habitat loss due to fire, logging for charcoal and timber, and clearing for mining. Environmentally damaging sapphire mines are common in this region of Madagascar.\n\nHowever sad the present story of the tree is, it is underlined by the name it acquired – Joseph Marie Henry Alfred Perrier de la Bâthie was a French botanist whose name was given to this ’discovered’ species. But he was also the man who in 1924 brought cochineal insects to Madagascar to counter strategic planting of opuntia cacti by local people. The cochineal quickly spread like a pest across the island, causing famine and wider societal changes.",
        },
        poem: "The tree called a scientific wonder\n\nthe tree called a wonder\n\n\n\nin the false cavities bark grows\n\nthirty adult people can take shelter in the trunk\n\na tree capable of engulfing\n\ncapable of living thousands of years\n\ncapable of storing water in its trunk\n\na tree under which you can boil coffee\n\na tree for which to pray\n\na tree that will pray for you\n\na tree whose flowers are pollinated by bats\n\na truly magnanimous tree\n\na tree that moves in the dark\n\na tree that has moved further and further north\n\nbut there is a limit to the north\n\n\n\nThe tree that refuses its name:\n\nthose who named it\n\nand us who choke it\n\nshare a surname",
        performers: "Vojtěch Šembera",
    },
    {
        sk: {
            title: "Prasličník Daintree",
            location: "dažďový prales Julaymba",
            protest: "blokáda Daintree",
            dating: "1983 – 1984",
            story: "Svojho času sa plánovala výstavba cesty cez dažďový prales v národnom parku Daintree. Miestni obyvatelia projekt neschvaľovali. Ich protest rýchlo prerástol do blokády, ku ktorej sa pripojili podporovatelia z celej krajiny. Keď dorazili buldozéry a polícia, ľudia liezli na stromy, pripútavali sa k nim a zatarasovali vozidlám prístup. Prišli médiá. Napriek protestom cestu dokončili, ale silné zrážky v období dažďov spôsobili zosuvy pôdy. Priamo počas oficiálneho otvorenia cesty uviazli autá v blate. Médiá napokon vzbudili medzinárodný záujem – a dažďový prales sa stal súčasťou Svetového dedičstva.",
        },
        en: {
            title: "Daintree pine",
            location: "Julaymba rainforest",
            protest: "Daintree blockade",
            dating: "1983-1984",
            story: "There was a time when road construction was planned through a rainforest in a Daintree national park. The project was not well received by locals. Their protest quickly grew into a blockade, and supporters came from all across the country. When the bulldozers and police arrived, people were climbing trees, chaining themselves to them, blocking the bulldozers. Media arrived. Despite the protests, the road was completed, but heavy rains of the wet season caused landslides. During the official opening of the road, the vehicles became stuck in mud.  Eventually, the media coverage drew international attention – and the rainforest was declared a World Heritage Site.",
        },
        poem: "the stories a rainforest contains, the rainy place\n\nslide with the mud to cover the road newly built\n\neven in October, the driest month\n\n\nusing the weight of bodies to gain minutes, hours, months\n\nthe stories a rainforest contains, the rainy place\n\nthe deep truths sedimented in our syntax[1], we carry some of the sediment around our roots",
        references: "[1] Klaus in Ben Lerner, Topeka School (Granta, 2020)",
        performers: "Anna Čonková",
    },
    {
        sk: {
            title: "Gledíčia trojtŕňová",
            location: "Benátky Giardini",
            protest: "",
            dating: "2019",
            story: "V blízkosti severného nárožia Pavilónu Českej republiky a Slovenskej republiky rastie stará statná gledíčia. Jedna z jej najväčších vetiev sa večer 8. júla 2019 zlomila a poškodila strechu Pavilónu, ktorý sa tak stal prakticky nepoužiteľným. V ten deň sa v Benátkach strhla prudká veterná smršť s rýchlosťou vetra až 90 km/h, ktorá vyvrátila stromy v celej oblasti. Odvtedy Pavilón, postavený v roku 1926, čakal na rekonštrukciu – až do roku 2024, keď ho dočasne zastrešili.\n\nBenátky so svojou lagúnou patria k oblastiam, ktoré sú najviac postihnuté klimatickými zmenami, znečistením, eróziou a poklesom pôdy. V správe UNESCO z roku 2023 sa uvádza, že zvyšovanie hladiny morí a extrémne počasie, spôsobené zmenou klímy spolu s masovým turizmom a výstavbou, ohrozujú staré budovy, stromy a prostredie Benátok. V správe sa odporúča zaradiť Benátky medzi chránené územia.",
        },
        en: {
            title: "Honey Locust",
            location: "Venice Giardini",
            protest: "",
            dating: "2019",
            story: "An old, large specimen of Honey Locust grows near the northern corner of the Czechoslovak pavilion. One of its main branches collapsed on the evening of 8 July 2019, causing damage to the roof of the pavilion and effectively making the entire pavilion unusable. In Venice that day, an exceptional windstorm reached up to 90 km/h. Entire trees were uprooted throughout the area. The pavilion, which was built in 1926, awaited reconstruction until 2024, when a temporary roof was eventually installed.\n\nVenice and its lagoon represent one of the areas most threatened by climate change, pollution, erosion, and subsidence. A UNESCO report from 2023 cited climate change-induced sea level rise and extreme weather, along with mass tourism and construction, as placing Venice's old buildings, trees, and landscapes at risk. The report recommended designating Venice as endangered.",
        },
        poem: "As we all know from school\n\nfor the forces of the external world\n\na building is but a postponement\n\n\nGlass\n\nshattering\n\n\nOn the night, a severe meteorological event swept through Venice,\n\na meteorological event so severe\n\ntrees, elsewhere, were uprooted\n\ngale force wind in this city\n\nwhose silence has more than once been called geological\n\n\nas for me, a branch broke,\n\n                                    crashing onto the pavilion roof\n\n\nGlass\n\nshattering\n\n\nTrees, trees have been there before me, touched the glass roof from below,\n\nearlier, a decade ago\n\n\nBut this story, story of this arboretum, begins with me and that July night,\n\na building paralysed by weather\n\nand all it could have contained\n\nfor years\n\n\nI arrived by water,\n\nI will depart by water\n\n\nEverything can be described in a way that will calm you\n\neventually",
        performers: "Anna Čonková, Vojtěch Šembera",
    },
    {
        sk: {
            title: "Sekvoja vždyzelená „Luna“",
            location: "Kalifornia",
            protest: "julia hill, pobyt na strome",
            dating: "1997 –1999",
            story: "Toto je príbeh mladej ženy menom Julia a sekvoje. Julia sa nevedela nečinne prizerať ako drevárska spoločnosť klčuje vzácne stromy, a tak vyliezla na tisícročnú sekvoju menom Luna, aby ju ochránila pred výrubom. V korune stromu zostala dva roky. Za pomoci aktivistov v teréne odolala mrazivému dažďu, silnému vetru a zastrašovaniu zo strany strážcov a drevorubačov. Rozhovory pre médiá poskytovala priamo zo stromu. Na zem zostúpila, až keď spoločnosť súhlasila so záchranou stromu a jeho okolia.",
        },
        en: {
            title: "Coast Redwood “Luna”",
            location: "California",
            protest: "julia hill tree-sit",
            dating: "1997-1999",
            story: "This is the story of a young woman named Julia and a redwood tree. She could not bear to watch the lumber company cut down redwoods. She climbed a 1,000-year-old sequoia tree named Luna to protect it from a logging company. She remained in the tree canopy for two years. With the help of activists on the ground, she withstood freezing rain, strong winds, and intimidation by security guards and loggers. She gave interviews to the media directly from the treetop. Only when the company agreed to spare the tree and the surrounding area did Julia climb down.",
        },
        poem: "In December 1997, a woman climbed into a sequoia,\n\na thousand-year-old sequoia,\n\nmarked to be logged—to make          front yard decks\n\n                                                           back yard decks\n\n                                                           front yard fences\n\n                                                           back yard fences\n\n                                                           chairs\n\n\nThe bark of the redwood is so thick, so moist,\n\nthat the tree can be hollowed out by lighting fire and still survive\n\n\nFirst winter: wind, storms, El Nino, loggers, wind water slashing branches crashing\n\nfor 16 hours she endured the storm\n\nSecond winter: snow and ice, loneliness,\n\non a platform 50m above the ground\n\nFor two years and eight days\n\n\n— not because we want it all\n\nbut because all that’s left is so little\n\n\nthe difference: endurance\n\nthe difference: endurance",
        performers: "Eva Šušková, Marek Kundlák",
    },
    {
        sk: {
            title: "Dub letný",
            location: "Somerset",
            protest: "Queen Camel Oak protest",
            dating: "2022",
            story: "Aktivisti prišli brániť prastarý dub, ktorý sa mal vyrúbať, aby uvoľnil miesto diaľnici. Obsadili pozemok okolo duba a zotrvali na ňom, pričom žiadali o preloženie cesty. Odvolali sa aj na najvyšší súd, ale neúspešne. Tento vyše 400-ročný strom, nazývaný dub Queen Camel, nechránil žiadny zákon. Napriek protestom, napriek petícii podpísanej mnohými ľuďmi, napriek lobovaniu miestnych politických kandidátov strom vyrúbali.",
        },
        en: {
            title: "Pedunculate Oak",
            location: "Somerset",
            protest: "Queen Camel Oak protest",
            dating: "2022",
            story: "When an ancient oak needed to be cut down to make way for a highway, activists arrived to defend it. They decided to stay and occupy the land around the oak, asking for relocation of the road. They even appealed to high court, but without success. This 400-year-old tree, which came to be known as the Queen Camel oak, was not protected by law. Despite the protests, despite a well-supported petition, despite lobbying from local political candidates, the tree was cut down.",
        },
        poem: "we cut the bodies that stand for our soul\n\n\n\nAugust, a boat-shaped month carried your body like a log\n\nOut of words I will build a boat that will carry your height\n\n                                                                                              upright\n\n\n\nThis is not a lament but retroactive resistance",
        performers: "Eva Šušková, Marek Kundlák",
    },
    {
        sk: {
            title: "Dub letný",
            location: "Hambašský les",
            protest: "Hambi Stays protest",
            dating: "2012 – 2020",
            story: "Našli sa ľudia, ktorí bránili starobylý Hambašský les pred vyklčovaním pre uhoľnú baňu. Spoločnosť na ťažbu hnedého uhlia dostala povolenie na výrub stromov, hoci les predstavoval vzácny, tisícročia nedotknutý ekosystém. Aktivisti strávili v lese šesť rokov a postavili si tam desiatky príbytkov na stromoch. Polícia dostala príkaz protestujúcich vysťahovať a zničiť ich domy. Nanešťastie, počas vyhosťovania, spadol zo stromu novinár a zomrel. Operáciu zastavili. O dva roky neskôr vláda súhlasila so zachovaním pravekého lesa.",
        },
        en: {
            title: "European Oak",
            location: "Hambach forest",
            protest: "Hambi Stays protest",
            dating: "2012 – 2020",
            story: "People defended an ancient Hambach Forest from being cleared for a coal mine. Although the forest is a rare ecosystem, untouched for thousands of years, a company had obtained a permit to cut down the trees for brown coal. The protesters stayed in the forest for six years, building dozens of tree houses. Police were sent to evict them and destroy their houses. Unfortunately, during the evictions, a journalist fell and died. The eviction was halted. Two years later, the government agreed to preserve the ancient forest.",
        },
        poem: "They said, it was a nice forest\n\n                        old forest\n\ntwelve-thousand-year-old forest\n\nbut-alas-it must go\n\n[The country needs energy, the country needs coal]\n\n\n\n\n\nWe said, it is a nice forest\n\n                        old forest\n\n                        twelve-thousand-year-old forest\n\nand go it cannot\n\n\n\nEight years of blockading that past tense\n\nuntil we make a different necessity visible\nEvolution is the capacity to remember what has helped[1]",
        references: "[1] Rudolf Jurolek, Bukolika (Modrý Peter, 2021)",
        performers: "Ivana Chrapková",
    },
    {
        sk: {
            title: "Jatoba",
            location: "Brazília",
            protest: "protest na nórskom veľvyslanectve v Brazílii",
            dating: "2021",
            story: "Na protest proti odlesňovaniu podnikli domorodí obyvatelia z organizácie Združenie pôvodných obyvateľov Brazílie (APIB) symbolickú akciu. Priniesli jatobu z dažďového pralesa k bráne veľvyslanectva krajiny, ktorá má prísne pravidlá proti odlesňovaniu a žiadali pre tento strom štatút utečenca. Veľvyslanectvo jatobu prijalo a zasadilo vo svojich priestoroch. Domorodí obyvatelia používajú miazgu jatoby na liečenie.",
        },
        en: {
            title: "Jatoba Tree",
            location: "Brasília",
            protest: "Protest at Norwegian Embassy in Brazil",
            dating: "2021",
            story: "To protest deforestation, indigenous people from the Articulation of Indigenous Peoples of Brazil (APIB) took a symbolic action. They brought a Jatoba tree from the rainforest to the gates of a foreign embassy. They sought refugee status for the tree at the embassy, which represented a country with strict rules against deforestation. The sap of the Jatoba tree is used for medicine by indigenous people. The embassy opened its gates and the Jatoba tree was planted on embassy grounds.",
        },
        poem: "To Whom It May Concern:\n\nThis is a request for refuge.\n\n\n\nTo Whom It May Concern:\n\nThe gates will open to the tree.\n\n\n\nFloating, roots covered in soil and cloth, balanced on a boat, on a truck,\n\nFloating, leaving, towards an arboretum perhaps, gates open, I enter\n\nwhat I left: condition incompatible with life (my life, and your life)\n\na storm blowing from paradise, forest burning\n\n\n\nAround my roots look for my resin, my animé\n\nthat will heal your lungs\n\nthat will heal your bronchitis\n\nthat will heal your inflammation\n\n\n\nwhat I left: the forest a war zone, condition incompatible with life\n\nThe deep truths sedimented in our syntax[1], I carry some of the sediment around my roots\n\n\n\nThe refugee tree, the first tree granted asylum",
        references: "[1] Klaus in Ben Lerner, Topeka School (Granta, 2020)",
        performers: "Ivana Chrapková, Marek Kundlák",
    },
    {
        sk: {
            title: "Libanonský céder",
            location: "cédrový les Barouk",
            protest: "",
            dating: "",
            story: "V libanonských starých cédrových lesoch rastú vyše 1000-ročné stromy, ktoré sú však, žiaľ, kriticky ohrozené zmenou klímy. Stúpajúce teploty vytláčajú cédre do vyšších nadmorských výšok, kde majú vhodné podmienky na rozmnožovanie. Dnes ich už nájdeme len v rezerváciách, napríklad v lese Barouk. Vedci predpokladajú, že do roku 2100 sa cédrom bude dariť iba na severnom cípe Libanonu.\n\nOkrem toho libanonské cédre podliehajú nákaze hmyzom, ktorá súvisí s otepľovaním a vysušovaním klímy. So vzrastajúcimi teplotami sa cedru libani prestáva dariť v jeho prirodzenej oblasti vo výške 1400 – 2000 m n. m. Deväť z dvanástich súčasných cédrových lesov sa už nachádza na náhorných plošinách, a tak iba tri z nich môžu uniknúť teplu presunom vyššie. Môže sa stať, že do roku 2100 zostane už len zopár cédrových lesov sústredených v malých severných častiach libanonského pohoria.",
        },
        en: {
            title: "Lebanese Cedar",
            location: "Barouk Cedar Forest",
            protest: "",
            dating: "",
            story: "Lebanon's ancient cedar forests are home to trees more than 1,000 years old, but they face a critical threat from climate change. Rising temperatures are pushing cedars to higher altitudes for reproduction. Currently, they grow only in limited areas in reserves such as the Barouk Forest. Scientists predict that by 2100 cedars may only thrive at the northern tip of Lebanon.\n\nLebanese Cedars also battle insect infestations linked to a warming, drying climate. As temperatures rise, cedrus libani no longer thrives in its natural region 1,400–2,000 metres above sea level. Nine of the twelve existing cedar forests are already located on summits, so only three may escape heat by migrating higher. By 2100, only a few cedar forests may remain in a small northern section of Mount Lebanon.",
        },
        poem: "shorter winters\n\nthe words spoken and then withdrawn\n\nonly their afterklang to accompany us\n\nsomething spoken and then withdrawn\n\na taste that hovers midair\n\n\n\nCedars need a minimum amount of snow to regenerate\n\nto need snow but just a little\n\nthe cones open up in the cold\n\nbut there is no further up for them to go\n\n\n\nshorter winters\n\nto say and then withdraw the said\n\nonly its afterklang to accompany us",
        performers: "Peter Mazalán",
    },
];
